import NavBar from "@/components/nav-bar/NavBar"
import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <NavBar />
          <div className="container">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
